# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AdventureWorks.sln'
  projectName: 'AdventureWorks.API.csproj'
  unitTestProjectName: 'AdventureWorks.UnitTests'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAdventureWorksApi
  displayName: 'Build Adventure Works API'

  steps:  
  - script: set
    displayName: print all variables

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'

  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      restoreSolution: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Adventure Works Solution (dotnet build)'
    inputs:
      command: 'build'
      projects: 'AdventureWorks.sln'
      arguments: '--configuration $(buildConfiguration) --framework  "net6.0" /p:EnvironmentName=Production /p:PackageLocation="$(build.artifactStagingDirectory)"'

  - task: DotNetCoreCLI@2
    displayName: 'Execute Adventure Works Unit Tests'
    inputs:
      command: 'test'
      projects: '''**/tests/$(unitTestProjectName).csproj'''
      testRunTitle: 'AdventureWorks UnitTests - $(Build.BuildNumber)'
      publishTestResults: true
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Adventure Works API Artifacts'
    inputs:
      command: publish
      publishWebProjects: True
      projects: '$(projectName)'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True      
   

