# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AdventureWorks.sln'
  unitTestProjectName: 'AdventureWorks.Data.Tests.dll'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAdventureWorksApi
  displayName: 'Build Adventure Works API'


  steps:  
  - script: set
    displayName: print all variables


  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'


  - task: NuGetCommand@2
    displayName: 'Restore NuGet Packages'
    inputs:
      restoreSolution: '$(solution)'


  - task: VSBuild@1
    displayName: 'Build Adventure Works Solution'
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:TargetFramework="net6.0" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'


  - task: VSTest@2
    displayName: 'Execute Adventure Works Unit Tests'
    inputs:
      testSelector: 'testAssemblies'
      testRunTitle: 'AdventureWorks_UnitTests'
      testAssemblyVer2: '**\'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
