# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AdventureWorks.sln'
  projectName: '**/src/AdventureWorks.API/AdventureWorks.API.csproj'
  unitTestProjectName: '**/tests/AdventureWorks.UnitTests/AdventureWorks.UnitTests.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscriptionConnectionName: 'Mick (Outlook) Azure Connection'
  azureAppResourceGroup: 'AdventureWorks-West-US-3'
  webApplicationNameProd: 'mick-adventureworks-api'
  webApplicationNameDev: 'mick-adventureworks-api-dev'

stages:
- stage: 'BuildApplication'
  displayName: 'Build Adventure Works App'

  jobs:
  - job: BuildAdventureWorksApi
    displayName: 'Build Adventure Works API'

    steps:  
    - script: set
      displayName: 'Print All YAML Build Pipleline Variables'

    - task: NuGetToolInstaller@1
      displayName: 'NuGet tool installer'

    - task: NuGetCommand@2
      name: 'NuGetRestore'
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      name: 'BuildSolution'
      displayName: 'Build Adventure Works Solution (dotnet build)'
      inputs:
        command: 'build'
        projects: 'AdventureWorks.sln'
        arguments: '--configuration $(buildConfiguration) --framework  "net6.0" /p:EnvironmentName=Production /p:PackageLocation="$(build.artifactStagingDirectory)"'

    - task: DotNetCoreCLI@2
      name: 'ExecuteUnitTests'
      displayName: 'Execute Adventure Works Unit Tests'
      inputs:
        command: 'test'
        projects: '$(solution)'
        testRunTitle: 'AdventureWorks UnitTests - $(Build.BuildNumber)'
        publishTestResults: true
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: DotNetCoreCLI@2
      name: 'Publish'
      displayName: 'Publish Adventure Works API Artifacts'
      inputs:
        command: publish
        publishWebProjects: true
        projects: '$(projectName)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework  "net6.0"'
        
    - task: PublishBuildArtifacts@1
      name: 'PublishBuildArtifacts'
      displayName: 'Publish AdventureWorks Build Artifacts'
      inputs:         
         ArtifactName: 'AdventureWorks'        

- stage: 'DeployToDev'
  displayName: 'Deploy Adventure Works Api to Development'
  dependsOn: 'BuildApplication'
  condition: and(succeeded('BuildApplication'), eq(variables['build.sourceBranch'], 'refs/heads/develop'))
  jobs:
  - deployment: DeployAdventureWorksApi
    displayName: 'Deploy Adventure Works Api to Development'
    environment: 'AdventureWorks-API-Dev'
    strategy:
      runOnce:
        deploy:    
          steps:  
          - script: set
            displayName: 'Print All YAML Release Pipleline Variables'

          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts Prior to Deployment'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'AdventureWorks'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Adventure Works Api'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscriptionConnectionName)
              appType: 'webApp'
              WebAppName: $(webApplicationNameDev)
              ResourceGroupName: $(azureAppResourceGroup)
              package: '$(System.ArtifactsDirectory)\**\*.zip'

- stage: 'DeployToProd'
  displayName: 'Deploy Adventure Works Api to Production'
  dependsOn: 
    - 'BuildApplication'
    - 'DeployToDev'
  jobs:
  - deployment: DeployAdventureWorksApi
    displayName: 'Deploy Adventure Works API to Production'
    environment: 'AdventureWorks-API-Production'
    strategy:
      runOnce:
        deploy:    
          steps: 
          - script: set
            displayName: 'Print All YAML Release Pipleline Variables'

          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts Prior to Deployment'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'AdventureWorks'
              downloadPath: '$(System.ArtifactsDirectory)'
              
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy Adventure Works Api'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: $(azureSubscriptionConnectionName)
              appType: 'webApp'
              WebAppName: $(webApplicationNameProd)
              ResourceGroupName: $(azureAppResourceGroup)
              package: '$(System.ArtifactsDirectory)\**\*.zip'
        
